version: "3"
services:
    web:
        build:
            context: ./app
            dockerfile: ./Dockerfile
        container_name: web-app-veins-recognition
        ports:
            - "5000:5000"
        expose:
            - "5000"
        volumes:
            - ./app:/app
